## numpy

In [99]:
import pandas as pd

In [100]:
import numpy as np

## 1-D Array

In [101]:
a = np.array([2, 3, 4, 5, 6])

In [102]:
print(f'{a.ndim}-D')

1-D


In [103]:
a[1]

3

In [104]:
a.shape

(5,)

## 2-D Array

In [105]:
b = np.array([[2, 3, 4, 5, 6]])

In [106]:
print(f'{b.ndim}-D')

2-D


In [107]:
b[0]

array([2, 3, 4, 5, 6])

In [108]:
b[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [109]:
b[0, 1]

3

In [110]:
b.shape

(1, 5)

In [111]:
c = np.array([[2, 3, 4, 5, 6], [7, 8, 9, 10, 11]])

In [112]:
print(f'{c.ndim}-D')

2-D


In [113]:
c.shape

(2, 5)

In [114]:
d = np.array([[2, 3, 4, 5, 6], [7, 8, 9, 10, 11], [12, 13, 14, 15, 16]])

In [115]:
print(f'{d.ndim}-D')

2-D


In [116]:
d[0, 1]

3

In [117]:
d.shape

(3, 5)

## 3-D Array

In [60]:
h = np.array([[[1]]])

In [118]:
print(f'{h.ndim}-D')

3-D


In [119]:
h[0, 0, 0]

1

In [143]:
g = np.array([[[1, 2, 3], [3, 2, 3]]])

In [144]:
g[0, 0, 1]

2

In [146]:
g.shape

(1, 2, 3)

In [147]:
t = np.array([[[[1]]]])

In [78]:
t.ndim

4

In [94]:
x1 = np.array([1, 2, 3, 4, 5])

In [95]:
x2 = x1

In [96]:
x1[2] = 10

In [97]:
x1

array([ 1,  2, 10,  4,  5])

In [98]:
x2

array([ 1,  2, 10,  4,  5])

In [169]:
p = np.array([1, '2', 3])
p

array(['1', '2', '3'], dtype='<U21')

In [170]:
lst = [1, 2, 3, 4, 5]

In [171]:
array = np.array(lst)

In [172]:
print(type(lst))

<class 'list'>


In [173]:
print(type(array))

<class 'numpy.ndarray'>


In [194]:
lst = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [197]:
lst[1, 1, 2]

15

In [198]:
lst.ndim

3

In [199]:
lst.shape

(2, 3, 3)