In [1]:
import numpy as np

In [2]:
images = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [28, 29, 30]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18], [31, 32, 33]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27], [34, 35, 36]],
    
])

In [3]:
images.ndim

3

In [4]:
images

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [28, 29, 30]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [31, 32, 33]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [34, 35, 36]]])

In [5]:
images.shape

(3, 4, 3)

In [6]:
images = images / 2

In [7]:
images

array([[[ 0.5,  1. ,  1.5],
        [ 2. ,  2.5,  3. ],
        [ 3.5,  4. ,  4.5],
        [14. , 14.5, 15. ]],

       [[ 5. ,  5.5,  6. ],
        [ 6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ],
        [15.5, 16. , 16.5]],

       [[ 9.5, 10. , 10.5],
        [11. , 11.5, 12. ],
        [12.5, 13. , 13.5],
        [17. , 17.5, 18. ]]])

In [8]:
arr = np.zeros(10)

In [9]:
arr[9] = 3

In [10]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 3.])

In [11]:
T = np.arange(10)
T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
r = np.arange(2, 100, 3)
r

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [13]:
l = np.linspace(0, 25, 4)
l

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

In [14]:
m = np.array([
     [0, 1, 2, 3, 4],  
     [4, 1, 2, 3, 5],  
     [0, 1, 2, 3, 6],  
     [0, 1, 2, 3, 7],  
])

m.shape

(4, 5)

In [16]:
j = np.arange(12)

In [19]:
j.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
normlize = np.arange(12)
normlize.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])